### PR TITLE
Update badges

### PR DESCRIPTION
**Pull request by tirr-c**

### CODE REVIEW

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by skystar-p** [comment]
어디갔어 호무야....

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by skystar-p** [comment]
@web-mighty-homu r+ 가즈아

**Comment by web-mighty-homu** [comment]
:pushpin: Commit beb2e37 has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit beb2e378b59f806f8f573fe09c8d8cf44e6610ea with merge 228fb31cd297e3a73bbe642236d10a646b79a5a7...

**Comment by tirr-c** [comment]
GAZUAAAAAAA

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/web-mighty/web-mighty/builds/324627029?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing 228fb31cd297e3a73bbe642236d10a646b79a5a7 to master...

**Pull request merged**
